"""Seed data for Just Talk - countries, interests, badges - COMPLETE SPEC"""

COUNTRIES = [
    {"code": "US", "name": "United States", "flag": "\U0001f1fa\U0001f1f8"},
    {"code": "GB", "name": "United Kingdom", "flag": "\U0001f1ec\U0001f1e7"},
    {"code": "CA", "name": "Canada", "flag": "\U0001f1e8\U0001f1e6"},
    {"code": "AU", "name": "Australia", "flag": "\U0001f1e6\U0001f1fa"},
    {"code": "DE", "name": "Germany", "flag": "\U0001f1e9\U0001f1ea"},
    {"code": "FR", "name": "France", "flag": "\U0001f1eb\U0001f1f7"},
    {"code": "JP", "name": "Japan", "flag": "\U0001f1ef\U0001f1f5"},
    {"code": "KR", "name": "South Korea", "flag": "\U0001f1f0\U0001f1f7"},
    {"code": "BR", "name": "Brazil", "flag": "\U0001f1e7\U0001f1f7"},
    {"code": "IN", "name": "India", "flag": "\U0001f1ee\U0001f1f3"},
    {"code": "MX", "name": "Mexico", "flag": "\U0001f1f2\U0001f1fd"},
    {"code": "ES", "name": "Spain", "flag": "\U0001f1ea\U0001f1f8"},
    {"code": "IT", "name": "Italy", "flag": "\U0001f1ee\U0001f1f9"},
    {"code": "NL", "name": "Netherlands", "flag": "\U0001f1f3\U0001f1f1"},
    {"code": "SE", "name": "Sweden", "flag": "\U0001f1f8\U0001f1ea"},
    {"code": "NO", "name": "Norway", "flag": "\U0001f1f3\U0001f1f4"},
    {"code": "DK", "name": "Denmark", "flag": "\U0001f1e9\U0001f1f0"},
    {"code": "FI", "name": "Finland", "flag": "\U0001f1eb\U0001f1ee"},
    {"code": "PL", "name": "Poland", "flag": "\U0001f1f5\U0001f1f1"},
    {"code": "RU", "name": "Russia", "flag": "\U0001f1f7\U0001f1fa"},
    {"code": "CN", "name": "China", "flag": "\U0001f1e8\U0001f1f3"},
    {"code": "TW", "name": "Taiwan", "flag": "\U0001f1f9\U0001f1fc"},
    {"code": "HK", "name": "Hong Kong", "flag": "\U0001f1ed\U0001f1f0"},
    {"code": "SG", "name": "Singapore", "flag": "\U0001f1f8\U0001f1ec"},
    {"code": "MY", "name": "Malaysia", "flag": "\U0001f1f2\U0001f1fe"},
    {"code": "PH", "name": "Philippines", "flag": "\U0001f1f5\U0001f1ed"},
    {"code": "ID", "name": "Indonesia", "flag": "\U0001f1ee\U0001f1e9"},
    {"code": "TH", "name": "Thailand", "flag": "\U0001f1f9\U0001f1ed"},
    {"code": "VN", "name": "Vietnam", "flag": "\U0001f1fb\U0001f1f3"},
    {"code": "NZ", "name": "New Zealand", "flag": "\U0001f1f3\U0001f1ff"},
    {"code": "IE", "name": "Ireland", "flag": "\U0001f1ee\U0001f1ea"},
    {"code": "PT", "name": "Portugal", "flag": "\U0001f1f5\U0001f1f9"},
    {"code": "BE", "name": "Belgium", "flag": "\U0001f1e7\U0001f1ea"},
    {"code": "CH", "name": "Switzerland", "flag": "\U0001f1e8\U0001f1ed"},
    {"code": "AT", "name": "Austria", "flag": "\U0001f1e6\U0001f1f9"},
    {"code": "ZA", "name": "South Africa", "flag": "\U0001f1ff\U0001f1e6"},
    {"code": "AR", "name": "Argentina", "flag": "\U0001f1e6\U0001f1f7"},
    {"code": "CL", "name": "Chile", "flag": "\U0001f1e8\U0001f1f1"},
    {"code": "CO", "name": "Colombia", "flag": "\U0001f1e8\U0001f1f4"},
    {"code": "PE", "name": "Peru", "flag": "\U0001f1f5\U0001f1ea"},
    {"code": "EG", "name": "Egypt", "flag": "\U0001f1ea\U0001f1ec"},
    {"code": "AE", "name": "United Arab Emirates", "flag": "\U0001f1e6\U0001f1ea"},
    {"code": "SA", "name": "Saudi Arabia", "flag": "\U0001f1f8\U0001f1e6"},
    {"code": "IL", "name": "Israel", "flag": "\U0001f1ee\U0001f1f1"},
    {"code": "TR", "name": "Turkey", "flag": "\U0001f1f9\U0001f1f7"},
    {"code": "GR", "name": "Greece", "flag": "\U0001f1ec\U0001f1f7"},
    {"code": "CZ", "name": "Czech Republic", "flag": "\U0001f1e8\U0001f1ff"},
    {"code": "RO", "name": "Romania", "flag": "\U0001f1f7\U0001f1f4"},
    {"code": "HU", "name": "Hungary", "flag": "\U0001f1ed\U0001f1fa"},
    {"code": "UA", "name": "Ukraine", "flag": "\U0001f1fa\U0001f1e6"},
]

# 200 interests across 15 categories (matching exact spec)
INTERESTS = [
    # Music (14)
    {"name": "indie rock", "category": "Music", "icon": "\U0001f3b8"},
    {"name": "hip hop", "category": "Music", "icon": "\U0001f3a4"},
    {"name": "electronic", "category": "Music", "icon": "\U0001f3a7"},
    {"name": "jazz", "category": "Music", "icon": "\U0001f3b7"},
    {"name": "classical", "category": "Music", "icon": "\U0001f3bb"},
    {"name": "r&b", "category": "Music", "icon": "\U0001f3b5"},
    {"name": "metal", "category": "Music", "icon": "\U0001f918"},
    {"name": "punk", "category": "Music", "icon": "\U0001f480"},
    {"name": "folk", "category": "Music", "icon": "\U0001fa95"},
    {"name": "country", "category": "Music", "icon": "\U0001f920"},
    {"name": "k-pop", "category": "Music", "icon": "\U0001f49c"},
    {"name": "lo-fi", "category": "Music", "icon": "\u2601\ufe0f"},
    {"name": "vaporwave", "category": "Music", "icon": "\U0001f334"},
    {"name": "ambient", "category": "Music", "icon": "\U0001f319"},
    # Gaming (15)
    {"name": "fps games", "category": "Gaming", "icon": "\U0001f52b"},
    {"name": "rpgs", "category": "Gaming", "icon": "\u2694\ufe0f"},
    {"name": "indie games", "category": "Gaming", "icon": "\U0001f579\ufe0f"},
    {"name": "mmorpgs", "category": "Gaming", "icon": "\U0001f3f0"},
    {"name": "horror games", "category": "Gaming", "icon": "\U0001f47b"},
    {"name": "puzzle games", "category": "Gaming", "icon": "\U0001f9e9"},
    {"name": "racing games", "category": "Gaming", "icon": "\U0001f3ce\ufe0f"},
    {"name": "fighting games", "category": "Gaming", "icon": "\U0001f94a"},
    {"name": "strategy games", "category": "Gaming", "icon": "\u265f\ufe0f"},
    {"name": "simulation games", "category": "Gaming", "icon": "\U0001f3ae"},
    {"name": "speedrunning", "category": "Gaming", "icon": "\u23f1\ufe0f"},
    {"name": "retro gaming", "category": "Gaming", "icon": "\U0001f47e"},
    {"name": "game dev", "category": "Gaming", "icon": "\U0001f4bb"},
    {"name": "esports", "category": "Gaming", "icon": "\U0001f3c6"},
    {"name": "board games", "category": "Gaming", "icon": "\U0001f3b2"},
    # Movies & TV (14)
    {"name": "horror movies", "category": "Movies & TV", "icon": "\U0001f9df"},
    {"name": "sci-fi", "category": "Movies & TV", "icon": "\U0001f680"},
    {"name": "anime", "category": "Movies & TV", "icon": "\U0001f338"},
    {"name": "documentaries", "category": "Movies & TV", "icon": "\U0001f4fd\ufe0f"},
    {"name": "true crime", "category": "Movies & TV", "icon": "\U0001f50d"},
    {"name": "reality tv", "category": "Movies & TV", "icon": "\U0001f4fa"},
    {"name": "film analysis", "category": "Movies & TV", "icon": "\U0001f3ac"},
    {"name": "foreign films", "category": "Movies & TV", "icon": "\U0001f30d"},
    {"name": "90s nostalgia", "category": "Movies & TV", "icon": "\U0001f4fc"},
    {"name": "sitcoms", "category": "Movies & TV", "icon": "\U0001f602"},
    {"name": "drama series", "category": "Movies & TV", "icon": "\U0001f3ad"},
    {"name": "action movies", "category": "Movies & TV", "icon": "\U0001f4a5"},
    {"name": "animated films", "category": "Movies & TV", "icon": "\u2728"},
    {"name": "thriller", "category": "Movies & TV", "icon": "\U0001f631"},
    # Books & Writing (13)
    {"name": "fantasy books", "category": "Books & Writing", "icon": "\U0001f409"},
    {"name": "poetry", "category": "Books & Writing", "icon": "\U0001f4dd"},
    {"name": "creative writing", "category": "Books & Writing", "icon": "\u270d\ufe0f"},
    {"name": "manga", "category": "Books & Writing", "icon": "\U0001f4d6"},
    {"name": "philosophy", "category": "Books & Writing", "icon": "\U0001f914"},
    {"name": "self-help", "category": "Books & Writing", "icon": "\U0001f331"},
    {"name": "history books", "category": "Books & Writing", "icon": "\U0001f4da"},
    {"name": "science books", "category": "Books & Writing", "icon": "\U0001f52c"},
    {"name": "biographies", "category": "Books & Writing", "icon": "\U0001f464"},
    {"name": "mystery novels", "category": "Books & Writing", "icon": "\U0001f50e"},
    {"name": "romance novels", "category": "Books & Writing", "icon": "\U0001f495"},
    {"name": "short stories", "category": "Books & Writing", "icon": "\U0001f4c3"},
    {"name": "journalism", "category": "Books & Writing", "icon": "\U0001f4f0"},
    # Art & Design (13)
    {"name": "digital art", "category": "Art & Design", "icon": "\U0001f3a8"},
    {"name": "photography", "category": "Art & Design", "icon": "\U0001f4f7"},
    {"name": "graphic design", "category": "Art & Design", "icon": "\U0001f5bc\ufe0f"},
    {"name": "fashion", "category": "Art & Design", "icon": "\U0001f457"},
    {"name": "tattoos", "category": "Art & Design", "icon": "\U0001f58b\ufe0f"},
    {"name": "street art", "category": "Art & Design", "icon": "\U0001f3a8"},
    {"name": "traditional art", "category": "Art & Design", "icon": "\U0001f58c\ufe0f"},
    {"name": "3d modeling", "category": "Art & Design", "icon": "\U0001f48e"},
    {"name": "animation", "category": "Art & Design", "icon": "\U0001f39e\ufe0f"},
    {"name": "interior design", "category": "Art & Design", "icon": "\U0001f3e0"},
    {"name": "architecture", "category": "Art & Design", "icon": "\U0001f3db\ufe0f"},
    {"name": "calligraphy", "category": "Art & Design", "icon": "\u2712\ufe0f"},
    {"name": "collage", "category": "Art & Design", "icon": "\U0001f4cb"},
    # Technology (14)
    {"name": "programming", "category": "Technology", "icon": "\U0001f4bb"},
    {"name": "ai & ml", "category": "Technology", "icon": "\U0001f916"},
    {"name": "web dev", "category": "Technology", "icon": "\U0001f310"},
    {"name": "cybersecurity", "category": "Technology", "icon": "\U0001f512"},
    {"name": "crypto", "category": "Technology", "icon": "\u20bf"},
    {"name": "vr/ar", "category": "Technology", "icon": "\U0001f97d"},
    {"name": "mobile dev", "category": "Technology", "icon": "\U0001f4f1"},
    {"name": "open source", "category": "Technology", "icon": "\U0001f513"},
    {"name": "linux", "category": "Technology", "icon": "\U0001f427"},
    {"name": "hardware", "category": "Technology", "icon": "\U0001f527"},
    {"name": "robotics", "category": "Technology", "icon": "\U0001f9be"},
    {"name": "data science", "category": "Technology", "icon": "\U0001f4ca"},
    {"name": "devops", "category": "Technology", "icon": "\u2699\ufe0f"},
    {"name": "ux design", "category": "Technology", "icon": "\U0001f3af"},
    # Sports & Fitness (14)
    {"name": "basketball", "category": "Sports & Fitness", "icon": "\U0001f3c0"},
    {"name": "soccer", "category": "Sports & Fitness", "icon": "\u26bd"},
    {"name": "running", "category": "Sports & Fitness", "icon": "\U0001f3c3"},
    {"name": "weightlifting", "category": "Sports & Fitness", "icon": "\U0001f3cb\ufe0f"},
    {"name": "yoga", "category": "Sports & Fitness", "icon": "\U0001f9d8"},
    {"name": "martial arts", "category": "Sports & Fitness", "icon": "\U0001f94b"},
    {"name": "swimming", "category": "Sports & Fitness", "icon": "\U0001f3ca"},
    {"name": "cycling", "category": "Sports & Fitness", "icon": "\U0001f6b4"},
    {"name": "climbing", "category": "Sports & Fitness", "icon": "\U0001f9d7"},
    {"name": "skateboarding", "category": "Sports & Fitness", "icon": "\U0001f6f9"},
    {"name": "surfing", "category": "Sports & Fitness", "icon": "\U0001f3c4"},
    {"name": "hiking", "category": "Sports & Fitness", "icon": "\U0001f97e"},
    {"name": "tennis", "category": "Sports & Fitness", "icon": "\U0001f3be"},
    {"name": "golf", "category": "Sports & Fitness", "icon": "\u26f3"},
    # Food & Drink (13)
    {"name": "cooking", "category": "Food & Drink", "icon": "\U0001f468\u200d\U0001f373"},
    {"name": "baking", "category": "Food & Drink", "icon": "\U0001f9c1"},
    {"name": "coffee", "category": "Food & Drink", "icon": "\u2615"},
    {"name": "wine", "category": "Food & Drink", "icon": "\U0001f377"},
    {"name": "craft beer", "category": "Food & Drink", "icon": "\U0001f37a"},
    {"name": "vegan", "category": "Food & Drink", "icon": "\U0001f96c"},
    {"name": "street food", "category": "Food & Drink", "icon": "\U0001f32e"},
    {"name": "sushi", "category": "Food & Drink", "icon": "\U0001f363"},
    {"name": "bbq", "category": "Food & Drink", "icon": "\U0001f356"},
    {"name": "spicy food", "category": "Food & Drink", "icon": "\U0001f336\ufe0f"},
    {"name": "food photography", "category": "Food & Drink", "icon": "\U0001f4f8"},
    {"name": "cocktails", "category": "Food & Drink", "icon": "\U0001f378"},
    {"name": "tea culture", "category": "Food & Drink", "icon": "\U0001f375"},
    # Lifestyle (14)
    {"name": "minimalism", "category": "Lifestyle", "icon": "\u25fb\ufe0f"},
    {"name": "travel", "category": "Lifestyle", "icon": "\u2708\ufe0f"},
    {"name": "astrology", "category": "Lifestyle", "icon": "\u2648"},
    {"name": "meditation", "category": "Lifestyle", "icon": "\U0001f9d8"},
    {"name": "spirituality", "category": "Lifestyle", "icon": "\U0001f549\ufe0f"},
    {"name": "sustainability", "category": "Lifestyle", "icon": "\u267b\ufe0f"},
    {"name": "thrifting", "category": "Lifestyle", "icon": "\U0001f45a"},
    {"name": "plant parent", "category": "Lifestyle", "icon": "\U0001fab4"},
    {"name": "pets", "category": "Lifestyle", "icon": "\U0001f415"},
    {"name": "cars", "category": "Lifestyle", "icon": "\U0001f697"},
    {"name": "motorcycles", "category": "Lifestyle", "icon": "\U0001f3cd\ufe0f"},
    {"name": "camping", "category": "Lifestyle", "icon": "\u26fa"},
    {"name": "diy projects", "category": "Lifestyle", "icon": "\U0001f528"},
    {"name": "collecting", "category": "Lifestyle", "icon": "\U0001f3af"},
    # Science (13)
    {"name": "astronomy", "category": "Science", "icon": "\U0001f52d"},
    {"name": "psychology", "category": "Science", "icon": "\U0001f9e0"},
    {"name": "biology", "category": "Science", "icon": "\U0001f9ec"},
    {"name": "physics", "category": "Science", "icon": "\u269b\ufe0f"},
    {"name": "climate science", "category": "Science", "icon": "\U0001f30d"},
    {"name": "neuroscience", "category": "Science", "icon": "\U0001f9ea"},
    {"name": "chemistry", "category": "Science", "icon": "\u2697\ufe0f"},
    {"name": "space exploration", "category": "Science", "icon": "\U0001f680"},
    {"name": "evolution", "category": "Science", "icon": "\U0001f995"},
    {"name": "mathematics", "category": "Science", "icon": "\u2797"},
    {"name": "oceanography", "category": "Science", "icon": "\U0001f30a"},
    {"name": "geology", "category": "Science", "icon": "\U0001faa8"},
    {"name": "quantum physics", "category": "Science", "icon": "\U0001f52e"},
    # Social & Politics (12)
    {"name": "politics", "category": "Social & Politics", "icon": "\U0001f5f3\ufe0f"},
    {"name": "activism", "category": "Social & Politics", "icon": "\u270a"},
    {"name": "economics", "category": "Social & Politics", "icon": "\U0001f4c8"},
    {"name": "social justice", "category": "Social & Politics", "icon": "\u2696\ufe0f"},
    {"name": "current events", "category": "Social & Politics", "icon": "\U0001f4f0"},
    {"name": "feminism", "category": "Social & Politics", "icon": "\u2640\ufe0f"},
    {"name": "lgbtq+", "category": "Social & Politics", "icon": "\U0001f3f3\ufe0f\u200d\U0001f308"},
    {"name": "mental health", "category": "Social & Politics", "icon": "\U0001f49a"},
    {"name": "education", "category": "Social & Politics", "icon": "\U0001f393"},
    {"name": "urban planning", "category": "Social & Politics", "icon": "\U0001f3d9\ufe0f"},
    {"name": "law", "category": "Social & Politics", "icon": "\u2696\ufe0f"},
    {"name": "nonprofits", "category": "Social & Politics", "icon": "\U0001f91d"},
    # Entertainment (13)
    {"name": "podcasts", "category": "Entertainment", "icon": "\U0001f399\ufe0f"},
    {"name": "stand-up comedy", "category": "Entertainment", "icon": "\U0001f3a4"},
    {"name": "memes", "category": "Entertainment", "icon": "\U0001f602"},
    {"name": "tiktok", "category": "Entertainment", "icon": "\U0001f4f1"},
    {"name": "streaming", "category": "Entertainment", "icon": "\U0001f4e1"},
    {"name": "youtube", "category": "Entertainment", "icon": "\u25b6\ufe0f"},
    {"name": "twitch", "category": "Entertainment", "icon": "\U0001f49c"},
    {"name": "asmr", "category": "Entertainment", "icon": "\U0001f3a7"},
    {"name": "magic tricks", "category": "Entertainment", "icon": "\U0001f3a9"},
    {"name": "trivia", "category": "Entertainment", "icon": "\u2753"},
    {"name": "karaoke", "category": "Entertainment", "icon": "\U0001f3b6"},
    {"name": "escape rooms", "category": "Entertainment", "icon": "\U0001f510"},
    {"name": "theme parks", "category": "Entertainment", "icon": "\U0001f3a2"},
    # Relationships (12)
    {"name": "dating", "category": "Relationships", "icon": "\U0001f495"},
    {"name": "friendships", "category": "Relationships", "icon": "\U0001f91d"},
    {"name": "long distance", "category": "Relationships", "icon": "\U0001f4cd"},
    {"name": "marriage", "category": "Relationships", "icon": "\U0001f492"},
    {"name": "parenting", "category": "Relationships", "icon": "\U0001f476"},
    {"name": "breakups", "category": "Relationships", "icon": "\U0001f494"},
    {"name": "situationships", "category": "Relationships", "icon": "\U0001f937"},
    {"name": "flirting", "category": "Relationships", "icon": "\U0001f60f"},
    {"name": "boundaries", "category": "Relationships", "icon": "\U0001f6a7"},
    {"name": "communication", "category": "Relationships", "icon": "\U0001f4ac"},
    {"name": "attachment styles", "category": "Relationships", "icon": "\U0001f517"},
    {"name": "love languages", "category": "Relationships", "icon": "\U0001f49d"},
    # Career (13)
    {"name": "entrepreneurship", "category": "Career", "icon": "\U0001f680"},
    {"name": "freelancing", "category": "Career", "icon": "\U0001f4bc"},
    {"name": "remote work", "category": "Career", "icon": "\U0001f3e0"},
    {"name": "job hunting", "category": "Career", "icon": "\U0001f50d"},
    {"name": "networking", "category": "Career", "icon": "\U0001f91d"},
    {"name": "side hustles", "category": "Career", "icon": "\U0001f4b0"},
    {"name": "startups", "category": "Career", "icon": "\U0001f984"},
    {"name": "investing", "category": "Career", "icon": "\U0001f4ca"},
    {"name": "personal finance", "category": "Career", "icon": "\U0001f4b5"},
    {"name": "career change", "category": "Career", "icon": "\U0001f504"},
    {"name": "leadership", "category": "Career", "icon": "\U0001f454"},
    {"name": "productivity", "category": "Career", "icon": "\u26a1"},
    {"name": "work-life balance", "category": "Career", "icon": "\u2696\ufe0f"},
    # Miscellaneous (13)
    {"name": "conspiracy theories", "category": "Miscellaneous", "icon": "\U0001f441\ufe0f"},
    {"name": "urban exploration", "category": "Miscellaneous", "icon": "\U0001f3da\ufe0f"},
    {"name": "lucid dreaming", "category": "Miscellaneous", "icon": "\U0001f4ad"},
    {"name": "paranormal", "category": "Miscellaneous", "icon": "\U0001f47b"},
    {"name": "aliens", "category": "Miscellaneous", "icon": "\U0001f47d"},
    {"name": "deep conversations", "category": "Miscellaneous", "icon": "\U0001f30c"},
    {"name": "night owls", "category": "Miscellaneous", "icon": "\U0001f989"},
    {"name": "overthinking", "category": "Miscellaneous", "icon": "\U0001f92f"},
    {"name": "nostalgia", "category": "Miscellaneous", "icon": "\U0001f4fa"},
    {"name": "languages", "category": "Miscellaneous", "icon": "\U0001f5e3\ufe0f"},
    {"name": "random facts", "category": "Miscellaneous", "icon": "\U0001f4a1"},
    {"name": "procrastination", "category": "Miscellaneous", "icon": "\U0001f605"},
    {"name": "existential thoughts", "category": "Miscellaneous", "icon": "\U0001f300"},
]

# 44 badges (complete spec)
BADGES = [
    # Polaroid Badges (7)
    {"name": "First Frame", "description": "Take your first Polaroid", "type": "polaroid", "rarity": "common", "threshold": 1, "material": "aluminum_white", "is_secret": False, "unlock_message": "You captured your first moment!"},
    {"name": "Memory Hoarder", "description": "Take 5 Polaroids", "type": "polaroid", "rarity": "common", "threshold": 5, "material": "aluminum_white", "is_secret": False, "unlock_message": "Building that collection."},
    {"name": "Snapshot Addict", "description": "Take 25 Polaroids", "type": "polaroid", "rarity": "uncommon", "threshold": 25, "material": "silver_cyan", "is_secret": False, "unlock_message": "You really like capturing moments."},
    {"name": "Archivist", "description": "Take 100 Polaroids", "type": "polaroid", "rarity": "rare", "threshold": 100, "material": "gold_magenta", "is_secret": False, "unlock_message": "Your gallery is impressive."},
    {"name": "Walking Gallery", "description": "Take 500 Polaroids", "type": "polaroid", "rarity": "legendary", "threshold": 500, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "A living museum of conversations."},
    {"name": "Polaroid God", "description": "Take 1000 Polaroids", "type": "polaroid", "rarity": "legendary", "threshold": 1000, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "Bow before the master of moments."},
    {"name": "???", "description": "Take 10000 Polaroids", "type": "polaroid", "rarity": "secret", "threshold": 10000, "material": "black_engraved", "is_secret": True, "unlock_message": "You have transcended."},
    # Conversation Badges (8)
    {"name": "First Words", "description": "Complete your first conversation", "type": "conversation", "rarity": "common", "threshold": 1, "material": "aluminum_white", "is_secret": False, "unlock_message": "You talked to a stranger!"},
    {"name": "Getting Warmed Up", "description": "Complete 10 conversations", "type": "conversation", "rarity": "common", "threshold": 10, "material": "aluminum_white", "is_secret": False, "unlock_message": "Getting comfortable."},
    {"name": "Social Creature", "description": "Complete 50 conversations", "type": "conversation", "rarity": "uncommon", "threshold": 50, "material": "silver_cyan", "is_secret": False, "unlock_message": "You actually like talking to strangers."},
    {"name": "Conversation Machine", "description": "Complete 100 conversations", "type": "conversation", "rarity": "uncommon", "threshold": 100, "material": "silver_cyan", "is_secret": False, "unlock_message": "You just keep going."},
    {"name": "Thousand Voices", "description": "Complete 500 conversations", "type": "conversation", "rarity": "rare", "threshold": 500, "material": "gold_magenta", "is_secret": False, "unlock_message": "So many strangers."},
    {"name": "Veteran", "description": "Complete 1000 conversations", "type": "conversation", "rarity": "legendary", "threshold": 1000, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "A true veteran of anonymous chat."},
    {"name": "Legend", "description": "Complete 5000 conversations", "type": "conversation", "rarity": "legendary", "threshold": 5000, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "Your legend grows."},
    {"name": "????", "description": "Complete 10000 conversations", "type": "conversation", "rarity": "secret", "threshold": 10000, "material": "black_engraved", "is_secret": True, "unlock_message": "What have you become?"},
    # Friend Badges (7)
    {"name": "Not Alone", "description": "Make your first friend", "type": "friend", "rarity": "common", "threshold": 1, "material": "aluminum_white", "is_secret": False, "unlock_message": "You found someone worth keeping."},
    {"name": "Small Circle", "description": "Make 5 friends", "type": "friend", "rarity": "common", "threshold": 5, "material": "aluminum_white", "is_secret": False, "unlock_message": "Quality over quantity."},
    {"name": "Popular", "description": "Make 10 friends", "type": "friend", "rarity": "uncommon", "threshold": 10, "material": "silver_cyan", "is_secret": False, "unlock_message": "People seem to like you."},
    {"name": "Connector", "description": "Make 25 friends", "type": "friend", "rarity": "uncommon", "threshold": 25, "material": "silver_cyan", "is_secret": False, "unlock_message": "Building bridges everywhere."},
    {"name": "Hub", "description": "Make 50 friends", "type": "friend", "rarity": "rare", "threshold": 50, "material": "gold_magenta", "is_secret": False, "unlock_message": "You are a social hub."},
    {"name": "Beloved", "description": "Make 100 friends", "type": "friend", "rarity": "legendary", "threshold": 100, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "Universally adored."},
    {"name": "Cult Leader", "description": "Make 500 friends", "type": "friend", "rarity": "legendary", "threshold": 500, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "Your following is concerning."},
    # Social Badges (9)
    {"name": "Grid Life", "description": "Connect Instagram", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Aesthetically linked."},
    {"name": "Loud Online", "description": "Connect Twitter/X", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Hot takes incoming."},
    {"name": "Attention Span", "description": "Connect TikTok", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "For your attention."},
    {"name": "Sound Identity", "description": "Connect Spotify", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Music says a lot."},
    {"name": "Server Dweller", "description": "Connect Discord", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Server hopper."},
    {"name": "Long Form", "description": "Connect YouTube", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Content creator energy."},
    {"name": "Live Wire", "description": "Connect Twitch", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Going live."},
    {"name": "Suit Energy", "description": "Connect LinkedIn", "type": "social", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Professional networking."},
    {"name": "Fully Doxxed", "description": "Connect all 8 social platforms", "type": "social", "rarity": "rare", "threshold": None, "material": "gold_magenta", "is_secret": False, "unlock_message": "You really put yourself out there."},
    # Special Badges (13)
    {"name": "Initiate", "description": "Complete the tutorial", "type": "special", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Welcome to Just Talk."},
    {"name": "Patron", "description": "Subscribe to VIP", "type": "special", "rarity": "rare", "threshold": None, "material": "gold_magenta", "is_secret": False, "unlock_message": "Supporting the cause."},
    {"name": "Ambassador", "description": "Promote Just Talk on TikTok", "type": "special", "rarity": "legendary", "threshold": None, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "Spreading the word."},
    {"name": "Old Soul", "description": "Be a member for 1 year", "type": "special", "rarity": "rare", "threshold": None, "material": "gold_magenta", "is_secret": False, "unlock_message": "One year of conversations."},
    {"name": "Ancient", "description": "Be a member for 2 years", "type": "special", "rarity": "legendary", "threshold": None, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "A true veteran."},
    {"name": "Marathon Mouth", "description": "Have a 4+ hour conversation", "type": "special", "rarity": "rare", "threshold": None, "material": "gold_magenta", "is_secret": False, "unlock_message": "You just kept talking."},
    {"name": "Time Dilation", "description": "Have an 8+ hour conversation", "type": "special", "rarity": "legendary", "threshold": None, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "Time stopped existing."},
    {"name": "Night Creature", "description": "Match at 3:33 AM", "type": "special", "rarity": "uncommon", "threshold": None, "material": "silver_cyan", "is_secret": False, "unlock_message": "Who else is awake?"},
    {"name": "Quick Draw", "description": "Polaroid within 60s of matching", "type": "special", "rarity": "uncommon", "threshold": None, "material": "silver_cyan", "is_secret": False, "unlock_message": "Fast capture."},
    {"name": "Paparazzi", "description": "Take 10+ Polaroids in a single conversation", "type": "special", "rarity": "rare", "threshold": None, "material": "gold_magenta", "is_secret": False, "unlock_message": "Document everything."},
    {"name": "Novelist", "description": "1000+ messages in one conversation", "type": "special", "rarity": "legendary", "threshold": None, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "You wrote a novel together."},
    {"name": "Cinderella", "description": "Conversation ends at midnight", "type": "special", "rarity": "secret", "threshold": None, "material": "black_engraved", "is_secret": True, "unlock_message": "The clock struck twelve."},
]

SOCIAL_PLATFORMS = [
    {"key": "instagram", "name": "Instagram", "badge_name": "Grid Life", "icon": "camera"},
    {"key": "twitter", "name": "Twitter/X", "badge_name": "Loud Online", "icon": "bird"},
    {"key": "tiktok", "name": "TikTok", "badge_name": "Attention Span", "icon": "music"},
    {"key": "spotify", "name": "Spotify", "badge_name": "Sound Identity", "icon": "headphones"},
    {"key": "discord", "name": "Discord", "badge_name": "Server Dweller", "icon": "chat"},
    {"key": "youtube", "name": "YouTube", "badge_name": "Long Form", "icon": "play"},
    {"key": "twitch", "name": "Twitch", "badge_name": "Live Wire", "icon": "stream"},
    {"key": "linkedin", "name": "LinkedIn", "badge_name": "Suit Energy", "icon": "briefcase"},
]
