"""Seed data for Just Talk - countries, interests, badges"""

COUNTRIES = [
    {"code": "US", "name": "United States", "flag": "🇺🇸"},
    {"code": "GB", "name": "United Kingdom", "flag": "🇬🇧"},
    {"code": "CA", "name": "Canada", "flag": "🇨🇦"},
    {"code": "AU", "name": "Australia", "flag": "🇦🇺"},
    {"code": "DE", "name": "Germany", "flag": "🇩🇪"},
    {"code": "FR", "name": "France", "flag": "🇫🇷"},
    {"code": "JP", "name": "Japan", "flag": "🇯🇵"},
    {"code": "KR", "name": "South Korea", "flag": "🇰🇷"},
    {"code": "BR", "name": "Brazil", "flag": "🇧🇷"},
    {"code": "IN", "name": "India", "flag": "🇮🇳"},
    {"code": "MX", "name": "Mexico", "flag": "🇲🇽"},
    {"code": "ES", "name": "Spain", "flag": "🇪🇸"},
    {"code": "IT", "name": "Italy", "flag": "🇮🇹"},
    {"code": "NL", "name": "Netherlands", "flag": "🇳🇱"},
    {"code": "SE", "name": "Sweden", "flag": "🇸🇪"},
    {"code": "NO", "name": "Norway", "flag": "🇳🇴"},
    {"code": "DK", "name": "Denmark", "flag": "🇩🇰"},
    {"code": "FI", "name": "Finland", "flag": "🇫🇮"},
    {"code": "PL", "name": "Poland", "flag": "🇵🇱"},
    {"code": "RU", "name": "Russia", "flag": "🇷🇺"},
    {"code": "CN", "name": "China", "flag": "🇨🇳"},
    {"code": "TW", "name": "Taiwan", "flag": "🇹🇼"},
    {"code": "HK", "name": "Hong Kong", "flag": "🇭🇰"},
    {"code": "SG", "name": "Singapore", "flag": "🇸🇬"},
    {"code": "MY", "name": "Malaysia", "flag": "🇲🇾"},
    {"code": "PH", "name": "Philippines", "flag": "🇵🇭"},
    {"code": "ID", "name": "Indonesia", "flag": "🇮🇩"},
    {"code": "TH", "name": "Thailand", "flag": "🇹🇭"},
    {"code": "VN", "name": "Vietnam", "flag": "🇻🇳"},
    {"code": "NZ", "name": "New Zealand", "flag": "🇳🇿"},
    {"code": "IE", "name": "Ireland", "flag": "🇮🇪"},
    {"code": "PT", "name": "Portugal", "flag": "🇵🇹"},
    {"code": "BE", "name": "Belgium", "flag": "🇧🇪"},
    {"code": "CH", "name": "Switzerland", "flag": "🇨🇭"},
    {"code": "AT", "name": "Austria", "flag": "🇦🇹"},
    {"code": "ZA", "name": "South Africa", "flag": "🇿🇦"},
    {"code": "AR", "name": "Argentina", "flag": "🇦🇷"},
    {"code": "CL", "name": "Chile", "flag": "🇨🇱"},
    {"code": "CO", "name": "Colombia", "flag": "🇨🇴"},
    {"code": "PE", "name": "Peru", "flag": "🇵🇪"},
    {"code": "EG", "name": "Egypt", "flag": "🇪🇬"},
    {"code": "AE", "name": "United Arab Emirates", "flag": "🇦🇪"},
    {"code": "SA", "name": "Saudi Arabia", "flag": "🇸🇦"},
    {"code": "IL", "name": "Israel", "flag": "🇮🇱"},
    {"code": "TR", "name": "Turkey", "flag": "🇹🇷"},
    {"code": "GR", "name": "Greece", "flag": "🇬🇷"},
    {"code": "CZ", "name": "Czech Republic", "flag": "🇨🇿"},
    {"code": "RO", "name": "Romania", "flag": "🇷🇴"},
    {"code": "HU", "name": "Hungary", "flag": "🇭🇺"},
    {"code": "UA", "name": "Ukraine", "flag": "🇺🇦"},
]

INTERESTS = [
    # Music
    {"name": "indie rock", "category": "Music", "icon": "🎸"},
    {"name": "hip hop", "category": "Music", "icon": "🎤"},
    {"name": "electronic", "category": "Music", "icon": "🎧"},
    {"name": "jazz", "category": "Music", "icon": "🎷"},
    {"name": "classical", "category": "Music", "icon": "🎻"},
    {"name": "r&b", "category": "Music", "icon": "🎵"},
    {"name": "metal", "category": "Music", "icon": "🤘"},
    {"name": "punk", "category": "Music", "icon": "⚡"},
    {"name": "folk", "category": "Music", "icon": "🪕"},
    {"name": "k-pop", "category": "Music", "icon": "💫"},
    {"name": "lo-fi", "category": "Music", "icon": "☁️"},
    {"name": "ambient", "category": "Music", "icon": "🌊"},
    # Gaming
    {"name": "fps games", "category": "Gaming", "icon": "🎯"},
    {"name": "rpgs", "category": "Gaming", "icon": "⚔️"},
    {"name": "indie games", "category": "Gaming", "icon": "🕹️"},
    {"name": "mmorpgs", "category": "Gaming", "icon": "🌐"},
    {"name": "horror games", "category": "Gaming", "icon": "👻"},
    {"name": "puzzle games", "category": "Gaming", "icon": "🧩"},
    {"name": "strategy games", "category": "Gaming", "icon": "♟️"},
    {"name": "speedrunning", "category": "Gaming", "icon": "⏱️"},
    {"name": "retro gaming", "category": "Gaming", "icon": "👾"},
    {"name": "esports", "category": "Gaming", "icon": "🏆"},
    {"name": "board games", "category": "Gaming", "icon": "🎲"},
    # Movies & TV
    {"name": "horror movies", "category": "Movies & TV", "icon": "🔪"},
    {"name": "sci-fi", "category": "Movies & TV", "icon": "🚀"},
    {"name": "anime", "category": "Movies & TV", "icon": "🌸"},
    {"name": "documentaries", "category": "Movies & TV", "icon": "🎬"},
    {"name": "true crime", "category": "Movies & TV", "icon": "🔍"},
    {"name": "reality tv", "category": "Movies & TV", "icon": "📺"},
    {"name": "film analysis", "category": "Movies & TV", "icon": "🎥"},
    {"name": "sitcoms", "category": "Movies & TV", "icon": "😂"},
    {"name": "drama series", "category": "Movies & TV", "icon": "🎭"},
    {"name": "animated films", "category": "Movies & TV", "icon": "✨"},
    # Books & Writing
    {"name": "fantasy books", "category": "Books & Writing", "icon": "🐉"},
    {"name": "poetry", "category": "Books & Writing", "icon": "📝"},
    {"name": "creative writing", "category": "Books & Writing", "icon": "✍️"},
    {"name": "manga", "category": "Books & Writing", "icon": "📖"},
    {"name": "philosophy", "category": "Books & Writing", "icon": "🤔"},
    {"name": "history books", "category": "Books & Writing", "icon": "📜"},
    {"name": "mystery novels", "category": "Books & Writing", "icon": "🕵️"},
    {"name": "romance novels", "category": "Books & Writing", "icon": "💕"},
    # Art & Design
    {"name": "digital art", "category": "Art & Design", "icon": "🎨"},
    {"name": "photography", "category": "Art & Design", "icon": "📷"},
    {"name": "graphic design", "category": "Art & Design", "icon": "🖌️"},
    {"name": "fashion", "category": "Art & Design", "icon": "👗"},
    {"name": "tattoos", "category": "Art & Design", "icon": "🖋️"},
    {"name": "street art", "category": "Art & Design", "icon": "🎨"},
    {"name": "3d modeling", "category": "Art & Design", "icon": "💎"},
    {"name": "animation", "category": "Art & Design", "icon": "🎞️"},
    # Technology
    {"name": "programming", "category": "Technology", "icon": "💻"},
    {"name": "ai & ml", "category": "Technology", "icon": "🤖"},
    {"name": "web dev", "category": "Technology", "icon": "🌐"},
    {"name": "cybersecurity", "category": "Technology", "icon": "🔒"},
    {"name": "crypto", "category": "Technology", "icon": "₿"},
    {"name": "vr/ar", "category": "Technology", "icon": "🥽"},
    {"name": "open source", "category": "Technology", "icon": "📂"},
    {"name": "linux", "category": "Technology", "icon": "🐧"},
    {"name": "robotics", "category": "Technology", "icon": "🦾"},
    {"name": "data science", "category": "Technology", "icon": "📊"},
    # Sports & Fitness
    {"name": "basketball", "category": "Sports & Fitness", "icon": "🏀"},
    {"name": "soccer", "category": "Sports & Fitness", "icon": "⚽"},
    {"name": "running", "category": "Sports & Fitness", "icon": "🏃"},
    {"name": "weightlifting", "category": "Sports & Fitness", "icon": "🏋️"},
    {"name": "yoga", "category": "Sports & Fitness", "icon": "🧘"},
    {"name": "martial arts", "category": "Sports & Fitness", "icon": "🥋"},
    {"name": "swimming", "category": "Sports & Fitness", "icon": "🏊"},
    {"name": "climbing", "category": "Sports & Fitness", "icon": "🧗"},
    {"name": "skateboarding", "category": "Sports & Fitness", "icon": "🛹"},
    {"name": "surfing", "category": "Sports & Fitness", "icon": "🏄"},
    {"name": "hiking", "category": "Sports & Fitness", "icon": "🥾"},
    # Food & Drink
    {"name": "cooking", "category": "Food & Drink", "icon": "👨‍🍳"},
    {"name": "baking", "category": "Food & Drink", "icon": "🧁"},
    {"name": "coffee", "category": "Food & Drink", "icon": "☕"},
    {"name": "wine", "category": "Food & Drink", "icon": "🍷"},
    {"name": "craft beer", "category": "Food & Drink", "icon": "🍺"},
    {"name": "vegan", "category": "Food & Drink", "icon": "🌱"},
    {"name": "street food", "category": "Food & Drink", "icon": "🌮"},
    {"name": "sushi", "category": "Food & Drink", "icon": "🍣"},
    {"name": "cocktails", "category": "Food & Drink", "icon": "🍸"},
    # Lifestyle
    {"name": "minimalism", "category": "Lifestyle", "icon": "◻️"},
    {"name": "travel", "category": "Lifestyle", "icon": "✈️"},
    {"name": "astrology", "category": "Lifestyle", "icon": "♈"},
    {"name": "meditation", "category": "Lifestyle", "icon": "🧘"},
    {"name": "sustainability", "category": "Lifestyle", "icon": "♻️"},
    {"name": "thrifting", "category": "Lifestyle", "icon": "🛍️"},
    {"name": "plant parent", "category": "Lifestyle", "icon": "🌿"},
    {"name": "pets", "category": "Lifestyle", "icon": "🐾"},
    {"name": "cars", "category": "Lifestyle", "icon": "🚗"},
    {"name": "camping", "category": "Lifestyle", "icon": "⛺"},
    {"name": "diy projects", "category": "Lifestyle", "icon": "🔧"},
    # Science
    {"name": "astronomy", "category": "Science", "icon": "🔭"},
    {"name": "physics", "category": "Science", "icon": "⚛️"},
    {"name": "neuroscience", "category": "Science", "icon": "🧠"},
    {"name": "chemistry", "category": "Science", "icon": "⚗️"},
    {"name": "space exploration", "category": "Science", "icon": "🛸"},
    {"name": "mathematics", "category": "Science", "icon": "➗"},
    {"name": "quantum physics", "category": "Science", "icon": "🌀"},
    # Social & Politics
    {"name": "politics", "category": "Social & Politics", "icon": "🗳️"},
    {"name": "activism", "category": "Social & Politics", "icon": "✊"},
    {"name": "economics", "category": "Social & Politics", "icon": "📈"},
    {"name": "mental health", "category": "Social & Politics", "icon": "💚"},
    {"name": "current events", "category": "Social & Politics", "icon": "📰"},
    {"name": "social justice", "category": "Social & Politics", "icon": "⚖️"},
    # Entertainment
    {"name": "podcasts", "category": "Entertainment", "icon": "🎙️"},
    {"name": "stand-up comedy", "category": "Entertainment", "icon": "😄"},
    {"name": "memes", "category": "Entertainment", "icon": "🤣"},
    {"name": "tiktok", "category": "Entertainment", "icon": "📱"},
    {"name": "streaming", "category": "Entertainment", "icon": "📡"},
    {"name": "youtube", "category": "Entertainment", "icon": "▶️"},
    {"name": "asmr", "category": "Entertainment", "icon": "🎧"},
    {"name": "trivia", "category": "Entertainment", "icon": "❓"},
    # Relationships
    {"name": "dating", "category": "Relationships", "icon": "💘"},
    {"name": "friendships", "category": "Relationships", "icon": "👫"},
    {"name": "long distance", "category": "Relationships", "icon": "🌍"},
    {"name": "breakups", "category": "Relationships", "icon": "💔"},
    {"name": "communication", "category": "Relationships", "icon": "💬"},
    {"name": "love languages", "category": "Relationships", "icon": "❤️"},
    # Career
    {"name": "entrepreneurship", "category": "Career", "icon": "🚀"},
    {"name": "freelancing", "category": "Career", "icon": "💼"},
    {"name": "remote work", "category": "Career", "icon": "🏠"},
    {"name": "startups", "category": "Career", "icon": "💡"},
    {"name": "investing", "category": "Career", "icon": "📊"},
    {"name": "personal finance", "category": "Career", "icon": "💰"},
    {"name": "productivity", "category": "Career", "icon": "⚡"},
    # Miscellaneous
    {"name": "conspiracy theories", "category": "Miscellaneous", "icon": "🕵️"},
    {"name": "lucid dreaming", "category": "Miscellaneous", "icon": "💭"},
    {"name": "paranormal", "category": "Miscellaneous", "icon": "👽"},
    {"name": "deep conversations", "category": "Miscellaneous", "icon": "🌌"},
    {"name": "night owls", "category": "Miscellaneous", "icon": "🦉"},
    {"name": "overthinking", "category": "Miscellaneous", "icon": "🌀"},
    {"name": "nostalgia", "category": "Miscellaneous", "icon": "📼"},
    {"name": "languages", "category": "Miscellaneous", "icon": "🗣️"},
    {"name": "random facts", "category": "Miscellaneous", "icon": "🧐"},
    {"name": "existential thoughts", "category": "Miscellaneous", "icon": "🌑"},
]

BADGES = [
    # Polaroid Badges
    {"name": "First Frame", "description": "Take your first Polaroid", "type": "polaroid", "rarity": "common", "threshold": 1, "material": "aluminum_white", "is_secret": False, "unlock_message": "You captured your first moment!"},
    {"name": "Memory Hoarder", "description": "Take 5 Polaroids", "type": "polaroid", "rarity": "common", "threshold": 5, "material": "aluminum_white", "is_secret": False, "unlock_message": "Building that collection."},
    {"name": "Snapshot Addict", "description": "Take 25 Polaroids", "type": "polaroid", "rarity": "uncommon", "threshold": 25, "material": "silver_cyan", "is_secret": False, "unlock_message": "You really like capturing moments."},
    {"name": "Archivist", "description": "Take 100 Polaroids", "type": "polaroid", "rarity": "rare", "threshold": 100, "material": "gold_magenta", "is_secret": False, "unlock_message": "Your gallery is impressive."},
    {"name": "Walking Gallery", "description": "Take 500 Polaroids", "type": "polaroid", "rarity": "legendary", "threshold": 500, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "A living museum of conversations."},
    # Conversation Badges
    {"name": "First Words", "description": "Complete your first conversation", "type": "conversation", "rarity": "common", "threshold": 1, "material": "aluminum_white", "is_secret": False, "unlock_message": "You talked to a stranger!"},
    {"name": "Getting Warmed Up", "description": "Complete 10 conversations", "type": "conversation", "rarity": "common", "threshold": 10, "material": "aluminum_white", "is_secret": False, "unlock_message": "Getting comfortable."},
    {"name": "Social Creature", "description": "Complete 50 conversations", "type": "conversation", "rarity": "uncommon", "threshold": 50, "material": "silver_cyan", "is_secret": False, "unlock_message": "You actually like talking to strangers."},
    {"name": "Conversation Machine", "description": "Complete 100 conversations", "type": "conversation", "rarity": "uncommon", "threshold": 100, "material": "silver_cyan", "is_secret": False, "unlock_message": "You just keep going."},
    {"name": "Thousand Voices", "description": "Complete 500 conversations", "type": "conversation", "rarity": "rare", "threshold": 500, "material": "gold_magenta", "is_secret": False, "unlock_message": "So many strangers."},
    # Friend Badges
    {"name": "Not Alone", "description": "Make your first friend", "type": "friend", "rarity": "common", "threshold": 1, "material": "aluminum_white", "is_secret": False, "unlock_message": "You found someone worth keeping."},
    {"name": "Small Circle", "description": "Make 5 friends", "type": "friend", "rarity": "common", "threshold": 5, "material": "aluminum_white", "is_secret": False, "unlock_message": "Quality over quantity."},
    {"name": "Popular", "description": "Make 10 friends", "type": "friend", "rarity": "uncommon", "threshold": 10, "material": "silver_cyan", "is_secret": False, "unlock_message": "People seem to like you."},
    {"name": "Connector", "description": "Make 25 friends", "type": "friend", "rarity": "uncommon", "threshold": 25, "material": "silver_cyan", "is_secret": False, "unlock_message": "Building bridges everywhere."},
    {"name": "Hub", "description": "Make 50 friends", "type": "friend", "rarity": "rare", "threshold": 50, "material": "gold_magenta", "is_secret": False, "unlock_message": "You are a social hub."},
    # Special Badges
    {"name": "Initiate", "description": "Complete the tutorial", "type": "special", "rarity": "common", "threshold": None, "material": "aluminum_white", "is_secret": False, "unlock_message": "Welcome to Just Talk."},
    {"name": "Patron", "description": "Subscribe to VIP", "type": "special", "rarity": "rare", "threshold": None, "material": "gold_magenta", "is_secret": False, "unlock_message": "Supporting the cause."},
    {"name": "Marathon Mouth", "description": "Have a 4+ hour conversation", "type": "special", "rarity": "rare", "threshold": None, "material": "gold_magenta", "is_secret": False, "unlock_message": "You just kept talking."},
    {"name": "Night Creature", "description": "Match at 3:33 AM", "type": "special", "rarity": "uncommon", "threshold": None, "material": "silver_cyan", "is_secret": False, "unlock_message": "Who else is awake?"},
    {"name": "Quick Draw", "description": "Polaroid within 60s of matching", "type": "special", "rarity": "uncommon", "threshold": None, "material": "silver_cyan", "is_secret": False, "unlock_message": "Fast capture."},
    {"name": "Novelist", "description": "1000+ messages in one conversation", "type": "special", "rarity": "legendary", "threshold": None, "material": "iridescent_holographic", "is_secret": False, "unlock_message": "You wrote a novel together."},
    {"name": "Cinderella", "description": "Conversation ends at midnight", "type": "special", "rarity": "secret", "threshold": None, "material": "black_engraved", "is_secret": True, "unlock_message": "The clock struck twelve."},
]
